# Generated by Django 5.0.6 on 2024-06-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_verb_location_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='person.person'),
        ),
    ]
