# Generated by Django 5.0.6 on 2024-06-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_event_related_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='verbs',
            field=models.ManyToManyField(blank=True, related_name='contributions', to='person.verb'),
        ),
        migrations.AddField(
            model_name='detailedrelationship',
            name='verbs',
            field=models.ManyToManyField(blank=True, related_name='detailed_relationships', to='person.verb'),
        ),
        migrations.AddField(
            model_name='event',
            name='verbs',
            field=models.ManyToManyField(related_name='events', to='person.verb'),
        ),
        migrations.AddField(
            model_name='person',
            name='verbs',
            field=models.ManyToManyField(blank=True, related_name='persons', to='person.verb'),
        ),
    ]
