services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lakehouse
      - POSTGRES_USER=lkh_user
      - POSTGRES_PASSWORD=lkh_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=lakehouse
      - DB_USER=lkh_user
      - DB_PASSWORD=lkh_password
      - DB_HOST=db

volumes:
  postgres_data:
